import type { NextPage } from "next";
import Head from "next/head";
import { AboutSection, HeroSection } from "../layouts";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Room-homepage | FEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <AboutSection />
    </>
  );
};

export default Home;
